name: Run Facebook Ads Report Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allow manual run

jobs:
  run-report:
    runs-on: ubuntu-latest

    env:
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
      GOOGLE_SHEET_CREDS: ${{ secrets.GOOGLE_SHEET_CREDS }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install facebook_business gspread gspread_dataframe oauth2client pandas

    - name: Run the script
      run: python report.py
